# name of the program (Minix service)
PROG=lab5

# source code files to be compiled
SRCS = lab5.c keyboard.c utils.c kbc.c timer.c vbe_functions.c sprite.c

# additional compilation flags
# "-Wall -Wextra -Werror -I . -std=c11 -Wno-unused-parameter" are already set
CPPFLAGS += -pedantic -D lab5

# list of library dependencies (for Lab 3, only LCF library)
DPADD += ${LIBLCF}
LDADD += -llcf

# include LCOM's makefile that does all the "heavy lifting"
.include <minix.lcom.mk>
